modLoader = "javafml"
loaderVersion = "[39,)"
license = "MIT License"
issueTrackerURL = "https://bumblecat.dev/issues/foodsicles"

[[mods]]
    modId = "baconators"
    version = "${file.jarVersion}"
    displayName = "Baconators"
    updateJSONURL = "https://bumblecat.dev/version/baconators"
    displayURL = "https://bumblecat.dev/"
    logoFile = "foodsicles.png"
    credits = ""
    authors = "Baijson"
    description = ''' Its much like bacon .. but, ON A STICK !! '''

[[dependencies.baconators]]
    modId = "forge"
    mandatory = true
    versionRange = "[39,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.baconators]]
    modId = "bumblecore"
    mandatory = true
    versionRange = "[1.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.baconators]]
    modId = "foodsicles"
    mandatory = true
    versionRange = "[1.0,)"
    ordering = "NONE"
    side = "BOTH"